--#include !/Cards/Card

Ambush = Card:new('Ambush', 'Start a Mob War (2 executed each turn).', 'Red', 1, false)

function Ambush:new()
    local o = {}
    setmetatable(o, self)
    self.__index = self
    return o
end

function Ambush:useScript(gameState, playerColor)
    HitList:startMobWar(2)
    return DECIDING_STATE
end

function Ambush:getLogString(gameState, playerColor)
    return Player[playerColor].steam_name .. ' started an Ambush'
end
